version: '3.9'

services:
    mongodb:
        image: mongo:latest
        container_name: DB
        env_file: ./.env
        ports:
            - 27017:27017
        volumes:
            - mongoDB:/data/db

    app:
        build: .
        env_file: ./.env
        ports:
            - 5011:5000

volumes:
    mongoDB:
